#!/bin/sh

xsetroot -cursor_name left_ptr &
set r rate 300 50 &
xset mouse 5 1 &
feh --bg-fill --randomize ~/Pictures/wp/* &
xrdb -merge .Xresources &
copyq &
picom &
pasystray &
polybar main &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX 

bspc config border_width         1
bspc config window_gap           0 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer   true
bspc config pointer_follows_focus   true

bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^9'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
